version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: holoo/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/Azmoon/backend
    volumes:
      - ..:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "8082:81"
      - "8084:82"
    volumes:
      - ../:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

  nodeapp:
    build:
      context: .
      dockerfile: DockerNodefile
    image: node-app
    container_name: nodeapp
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ../Amazon_NodeJs:/usr/src/app
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
